### ISSUE TITLE
Genifile

### ISSUE THREAD

**Issue by Joannakrol** [patscott/gambit_1.0#5]

**Comment by patscott** [comment]
Hello - please describe the issue if you would like it addressed; otherwise we will assume this is spam and close it.
Thanks - Pat

**Comment by Joannakrol** [comment]
I send a discribe of issus and sent photo of issues but the staff is not
answer...i do not anything action on resposytorum inflaton/mchrzasz.
umvisible is follow marcin chrzaszcz, i am not in friends marcin
chrzaszcz.... is issues with code or users blocked me... i want to learn
code

W dniu czwartek, 1 marca 2018 patscott <notifications@github.com>
napisał(a):

**Comment by patscott** [comment]
I'm sorry, don't understand your issue.  This issue tracker is for problems with the GAMBIT 1.0 release.   Please email Marcin (marcin.chrzaszcz@cern.ch) if your problem is something to do with some other code of his.

**Comment by Joannakrol** [comment]
I do not want to askedmhim about this. That is his problem. So i delate my account and that will be the best thing  what i can do. It was nice to meet every one bye bee satisfactioin
