### ISSUE TITLE
Respect umask when writing output

### ISSUE THREAD

**Issue by agbuckley** [patscott/gambit_1.0#6]
It seems that when writing the output runs directory, subdirectories, and files therein, gambit assigns null Unix access permissions to the "group" and "other" categories, even if the default umask for file and dir creation is more permissive. This can create surprise problems when sharing gambit outputs between users on a system. It would be good if gambit could respect the default file- and dir-creation permissions.

umask explanation: https://askubuntu.com/questions/44542/what-is-umask-and-how-does-it-work so I think this should be working automatically: is the *gambit* code explicitly setting the process-level umask (is that even possible?) or explicitly chmoding the created files?

**Comment by agbuckley** [comment]
From Andrew F:

"""
Is it caused by line 27 of contrib/mkpath/src/mkpath.c

https://github.com/patscott/gambit/blob/9dc1229010d55d8b82661cbe04a8d3a8cf0db857/contrib/mkpath/src/mkpath.c#L27

it makes nested directories by 

mkdir(opath, S_IRWXU)

where the code S_IRWXU means read/write/execute for user. mkdir(opath, ACCESSPERMS) would give 0777. More info here about other arguments, https://techoverflow.net/2013/04/05/how-to-use-mkdir-from-sysstat-h/. If that is causing this behaviour, which one do we want to change it to?
"""

**Comment by agbuckley** [comment]
I think the correct setting is ACCESSPERMS. This interacts with the system umask to set appropriate permissions, cf. a little test program:

    #include "sys/stat.h"
    #include <fstream>
    using namespace std;

    int main(int argc, char** argv) {
      mkdir("testdir", ACCESSPERMS);
      ofstream fp("testdir/testfile.txt");
      fp << "BLAH\n";
      fp.close();
      return 0;
    }

And here's how things look when I run it on my system, with my default 002 umask printed at the top:

    $ umask
    0002
    $ ls testdir/ -ld
    drwxrwxr-x 2 andy andy 4.0K Mar 20 11:12 testdir/
    $ ls testdir/ -l
    total 4.0K
    -rw-rw-r-- 1 andy andy 5 Mar 20 11:12 testfile.txt

So the very inclusive ACCESSPERMS setting in the code gets downgraded to apply whatever permissions constraints are set by the user, which is how it should be, and this also propagates to the files written in these dirs.

Who wants to make the change? I'm happy to do so, if people agree and specify the preferred branch for this to go to (I may also copy it to a ColliderBit branch, just for personal convenience: hopefully the merge will handle that ok).

**Comment by andrewfowlie** [comment]
@patscott can this be pushed to master?

**Comment by patscott** [comment]
Hi - just for future reference, this should have been raised on the internal repo (patscott/gambit) or the current version (patscott/gambit_1.1).

Andrew, I think the way this is supposed to work is that you attach your pull request to this thread somehow -- could you do that please?  

I don't have time to test the fix and deal with the request immediately, but it also shouldn't be the case that I always need to be the one to do so anyway; Andy, when Andrew has attached his pull request to this, can you test it and see if you have sufficient permissions to accept it and close the issue?

Thanks - Pat

**Comment by andrewfowlie** [comment]
I'm a bit confused about how this is all organized. Let me show you how this would ordinarily work, but I'm confused about all the repos we have.

**Comment by andrewfowlie** [comment]
Now, maybe I should have done this on the patscott/gambit repo, not this one?

**Comment by patscott** [comment]
Yeah, it should be on https://github.com/patscott/gambit.  I can't find any way to move the issue or the pull request to that repo, so Andrew, please open a new pull request on that repo instead.  I'll close this issue and the pull request on this one.
